# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: productionpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  prvw.space:
    env:
      db_password: seequilPassword01!
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "T{r%0(+/M1p$bsIuS@x[(35[qV[wKt=k#I{;Kxp}n&Hp{YWN>65{nCP6q*3syXzf"
      secure_auth_key: "a$1=BY4A`]}*wLm8oXow/7mVbmL!U4WXCsbW2u7h8n&>^CnZAr+0uNO;K:ncPzx["
      logged_in_key: "%!J3hg$:%za49ev3p_k5I?p5&k+m^?h_67G:|_|>B(xS4tZi=}sMym&bc+=umb25"
      nonce_key: "jjbaE!=AAX_ThzR^9;-7NbD#fOJl;;G@+W6,N-}0&6]+H0m;<5rp/Q|}MO)g|C{v"
      auth_salt: "BC0tRtrt]Bl|9L!V?aNkX{0?:OJdq2ADoY{x^gz7a4qjvh8i::7x,{_G+<k3DdM^"
      secure_auth_salt: ".-vNm]UT]?5qij_W}yMCg&LIJ[XT(j}8lYW,O3v&_/b;SMY}i)X!-!P1d;/cAcY}"
      logged_in_salt: "&b:u>K$1M,c3b+_1GF/RyRH:(0%Hv]Recx08LCZp_ltbIA.}i2E.TIV0Xp_jFaas"
      nonce_salt: "(&HOQP/k0,k-1O-Dr+{AVZ9*,,iP.&.=%aB][oFE`?Za,DInZU)#X30Y0D,VmB^K"
# NOTE: Changes made here
